osc=yes
border=yes
osd-level=1
osd-duration=1000
hr-seek=yes

# ==========    SCALERS AND SHADERS    ==========

# Default was (because of profile=gpu-hq):
# scale=spline36
# cscale=spline36
# dscale=mitchell


cscale=ewa_lanczossoft                          # Chroma up&downscaler

gpu-shader-cache-dir='~/.config/shaders/cache'         # https://mpv.io/manual/stable/#options-gpu-shader-cache-dir

###### Luma up (uncomment FSRCNNX or SSimSuperRes, not both)
#glsl-shader="~~/shaders/FSRCNNX_x2_8-0-4-1_LineArt.glsl" # mathematically best, most expensive, more powerful, but tend to cause overshoot
glsl-shader="~/.config/shaders/SSimSuperRes.glsl"               # really good, a little cheaper for the GPU
scale=ewa_lanczossharp

###### Luma down
glsl-shader="~/.config/shaders/SSimDownscaler.glsl"
dscale=mitchell
linear-downscaling=no
correct-downscaling=yes

# ==========    AUDIO    ==========

volume=50
audio-pitch-correction=yes 

# ==========    SUBTITLES    ==========

demuxer-mkv-subtitle-preroll=yes                # https://mpv.io/manual/stable/#options-mkv-subtitle-preroll
sub-ass-vsfilter-blur-compat=no                 # https://mpv.io/manual/stable/#options-sub-ass-vsfilter-aspect-compat
sub-fix-timing=yes                               # https://mpv.io/manual/stable/#options-sub-fix-timing
sub-auto=fuzzy                                  # https://mpv.io/manual/stable/#options-no-sub-auto

sub-font='NotoSerifCJKJP-Regular'                  # Specify font to use for subtitles that do not themselves specify a particular font
sub-font-size=16
sub-color='#FFFFFFFF'
sub-border-color='#FF000000'
sub-border-size=2.0
sub-shadow-offset=0
sub-spacing=0.0

ytdl-raw-options='ignore-config=,sub-langs="en,en-US",write-subs=,write-auto-subs='
