# IMPORTANT: enable mpd as a USER with systemctl --user enable mpd.
music_directory "/dvs/dv1/Music/rmpcMain/youtube/"
playlist_directory "/dvs/dv1/Music/rmpcMain/youtube"
db_file "/dvs/dv1/Music/rmpcMain/mpddb"
pid_file "~/.cache/mpd/pid"

state_file "~/.mpd/state"


input {
  plugin "curl"
}

audio_output {
  type  "alsa"
  name  "My ALSA Device"
  mixer_type "software"
}

decoder {
    plugin "wildmidi"
    enabled "no"
}

bind_to_address "127.0.0.1" #"/tmp/mpd_socket"
auto_update "yes"
restore_paused "yes"
max_output_buffer_size "16384"
port "6600"
